{
 This file is part of the IPlugDesigner. Copyright (C) the IPlugDesigner developer.
 See LICENSE.txt for more info.
}

unit uFauIcons;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils;

const
  ICONS_FAU: array[0..154] of string = (
    'ICON_FAU_ADR',
    'ICON_FAU_ADSR',
    'ICON_FAU_AHDSR',
    'ICON_FAU_AR',
    'ICON_FAU_ARMRECORDING',
    'ICON_FAU_ARPCHORD',
    'ICON_FAU_ARPDOWN',
    'ICON_FAU_ARPDOWNANDUP',
    'ICON_FAU_ARPDOWNUP',
    'ICON_FAU_ARPPLAYORDER',
    'ICON_FAU_ARPRANDOM',
    'ICON_FAU_ARPUP',
    'ICON_FAU_ARPUPANDOWN',
    'ICON_FAU_ARPUPDOWN',
    'ICON_FAU_ARROWS_HORZ',
    'ICON_FAU_ARROWS_VERT',
    'ICON_FAU_AUTOMATION_2P',
    'ICON_FAU_AUTOMATION_3P',
    'ICON_FAU_AUTOMATION_4P',
    'ICON_FAU_BACKWARD',
    'ICON_FAU_BLUETOOTH',
    'ICON_FAU_CARET_DOWN',
    'ICON_FAU_CARET_LEFT',
    'ICON_FAU_CARET_RIGHT',
    'ICON_FAU_CARET_UP',
    'ICON_FAU_CLOSE',
    'ICON_FAU_COPY',
    'ICON_FAU_CPU',
    'ICON_FAU_CUTTER',
    'ICON_FAU_DIGITAL_COLON',
    'ICON_FAU_DIGITAL_DOT',
    'ICON_FAU_DIGITAL0',
    'ICON_FAU_DIGITAL1',
    'ICON_FAU_DIGITAL2',
    'ICON_FAU_DIGITAL3',
    'ICON_FAU_DIGITAL4',
    'ICON_FAU_DIGITAL5',
    'ICON_FAU_DIGITAL6',
    'ICON_FAU_DIGITAL7',
    'ICON_FAU_DIGITAL8',
    'ICON_FAU_DIGITAL9',
    'ICON_FAU_DISKIO',
    'ICON_FAU_DRUMPAD',
    'ICON_FAU_DUPLICATE',
    'ICON_FAU_ERASER',
    'ICON_FAU_FFWD',
    'ICON_FAU_FILTER_BANDPASS',
    'ICON_FAU_FILTER_BELL',
    'ICON_FAU_FILTER_BYPASS',
    'ICON_FAU_FILTER_HIGHPASS',
    'ICON_FAU_FILTER_LOWPASS',
    'ICON_FAU_FILTER_NOTCH',
    'ICON_FAU_FILTER_REZ_HIGHPASS',
    'ICON_FAU_FILTER_REZ_LOWPASS',
    'ICON_FAU_FILTER_SHELVING_HI',
    'ICON_FAU_FILTER_SHELVING_LO',
    'ICON_FAU_FOLDBACK',
    'ICON_FAU_FORWARD',
    'ICON_FAU_H_EXPAND',
    'ICON_FAU_HARDCLIP',
    'ICON_FAU_HARDCLIPCURVE',
    'ICON_FAU_HEADPHONES',
    'ICON_FAU_KEYBOARD',
    'ICON_FAU_LOCK',
    'ICON_FAU_LOGO_AAX',
    'ICON_FAU_LOGO_ABLETONLINK',
    'ICON_FAU_LOGO_AU',
    'ICON_FAU_LOGO_AUDACITY',
    'ICON_FAU_LOGO_AUDIOBUS',
    'ICON_FAU_LOGO_CUBASE',
    'ICON_FAU_LOGO_FL',
    'ICON_FAU_LOGO_JUCE',
    'ICON_FAU_LOGO_LADSPA',
    'ICON_FAU_LOGO_LIVE',
    'ICON_FAU_LOGO_LV2',
    'ICON_FAU_LOGO_PROTOOLS',
    'ICON_FAU_LOGO_RACKEXT',
    'ICON_FAU_LOGO_REAPER',
    'ICON_FAU_LOGO_REASON',
    'ICON_FAU_LOGO_REWIRE',
    'ICON_FAU_LOGO_STUDIOONE',
    'ICON_FAU_LOGO_TRACKTION',
    'ICON_FAU_LOGO_VST',
    'ICON_FAU_LOGO_WAVEFORM',
    'ICON_FAU_LOOP',
    'ICON_FAU_METRONOME',
    'ICON_FAU_MICROPHONE',
    'ICON_FAU_MIDIPLUG',
    'ICON_FAU_MODRANDOM',
    'ICON_FAU_MODSAWDOWN',
    'ICON_FAU_MODSAWUP',
    'ICON_FAU_MODSH',
    'ICON_FAU_MODSINE',
    'ICON_FAU_MODSQUARE',
    'ICON_FAU_MODTRI',
    'ICON_FAU_MODULARPLUG',
    'ICON_FAU_MONO',
    'ICON_FAU_MUTE',
    'ICON_FAU_NEXT',
    'ICON_FAU_OPEN',
    'ICON_FAU_PASTE',
    'ICON_FAU_PAUSE',
    'ICON_FAU_PEN',
    'ICON_FAU_PHASE',
    'ICON_FAU_PLAY',
    'ICON_FAU_POINTER',
    'ICON_FAU_POWERSWITCH',
    'ICON_FAU_PRESET_A',
    'ICON_FAU_PRESET_AB',
    'ICON_FAU_PRESET_B',
    'ICON_FAU_PRESET_BA',
    'ICON_FAU_PREV',
    'ICON_FAU_PUNCH_IN',
    'ICON_FAU_PUNCH_OUT',
    'ICON_FAU_RAM',
    'ICON_FAU_RANDOM_1DICE',
    'ICON_FAU_RANDOM_2DICE',
    'ICON_FAU_RECORD',
    'ICON_FAU_REDO',
    'ICON_FAU_REPEAT_ONE',
    'ICON_FAU_REPEAT',
    'ICON_FAU_REW',
    'ICON_FAU_ROUNDSWITCH_OFF',
    'ICON_FAU_ROUNDSWITCH_ON',
    'ICON_FAU_SAVE',
    'ICON_FAU_SAVEAS',
    'ICON_FAU_SCISSORS',
    'ICON_FAU_SHUFFLE',
    'ICON_FAU_SLIDER_ROUND_1',
    'ICON_FAU_SLIDER_ROUND_2',
    'ICON_FAU_SLIDER_ROUND_3',
    'ICON_FAU_SLIDERHANDLE_1',
    'ICON_FAU_SLIDERHANDLE_2',
    'ICON_FAU_SOFTCLIP',
    'ICON_FAU_SOFTCLIPCURVE',
    'ICON_FAU_SOLO',
    'ICON_FAU_SPEAKER',
    'ICON_FAU_SQUARESWITCH_OFF',
    'ICON_FAU_SQUARESWITCH_ON',
    'ICON_FAU_STEREO',
    'ICON_FAU_STOP',
    'ICON_FAU_THUNDERBOLT',
    'ICON_FAU_TIMESELECT',
    'ICON_FAU_UNDO',
    'ICON_FAU_UNLOCK',
    'ICON_FAU_USB',
    'ICON_FAU_V_EXPAND',
    'ICON_FAU_VROUNDSWITCH_OFF',
    'ICON_FAU_VROUNDSWITCH_ON',
    'ICON_FAU_VSQUARESWITCH_OFF',
    'ICON_FAU_VSQUARESWITCH_ON',
    'ICON_FAU_WAVEFORM',
    'ICON_FAU_XLRPLUG',
    'ICON_FAU_ZOOMIN',
    'ICON_FAU_ZOOMOUT');

  function StrToFauIcon(const s: string): string;

implementation

uses Math, StrUtils;

function StrToFauIcon(const s: string): string;
var
  i: integer;
begin
  result := s;
  i := AnsiIndexStr(s, ICONS_FAU);
  if i < 0 then
    exit;
  result := WideChar($f101 + i);
end;


end.

